# -*- coding: utf-8 -*-
"""houseprediction

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ACxo5WvUB6NnokXOId9AMbfT6ZnX696Z
"""



"""##Univariate Analysis"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

data = pd.read_csv('/content/House Price India.csv')
print(data.head())

data.head

data.shape

sns.histplot(data['Date'])

sns.distplot(data.Date)
sns.displot(data.Lattitude)

sns.countplot(data['number of bathrooms'])

plt.pie(data.Price)
plt.show()

x = data['number of bedrooms'].value_counts()
plt.pie(x.values,
		labels=x.index,
		autopct='%1.1f%%')
plt.show()

sns.barplot(x=data.Date.value_counts().index,y=data.Date.value_counts())

sns.barplot(x=data.Lattitude.value_counts().index,y=data.Lattitude.value_counts())

"""##Bivariate analysis"""

import matplotlib.pyplot as plt
plt.figure(figsize=(15, 5))
sns.barplot(x=data['id'], y=data['number of bedrooms'])
plt.xticks(rotation='vertical')

sns.scatterplot(x=data['number of floors'],
				y=data['lot area'])

sns.lineplot(x=data.Date,y=data.Lattitude)

sns.scatterplot(x=data.Date,y=data.Lattitude)

plt.boxplot(data)

sns.jointplot(x='Built Year',y='Price',data=data)

fig,ax = plt.subplots(2,2)
ax[0,0].plot(data.Date , data.Price)
ax[1,0].scatter(data.Date , data.Price)
ax[1,1].bar(data.Date , data.Price)

sns.pairplot(data)

sns.heatmap(data.corr(),annot=True)